name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

# ===============================================================
# DEPENDÊNCIAS DE PRODUÇÃO
# Pacotes que serão incluídos no seu aplicativo final.
# ===============================================================
dependencies:
  flutter:
    sdk: flutter

  # UI e Utilitários
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1
  image_picker: ^0.8.7+5
  file_picker: ^6.1.1
  mime: ^1.0.5
  shelf: ^1.4.0
  shelf_proxy: ^1.0.4

  # Rede e Serialização (Runtime)
  dio: ^5.4.3
  json_annotation: ^4.9.0
  chopper: ^6.0.0

# ===============================================================
# DEPENDÊNCIAS DE DESENVOLVIMENTO
# Ferramentas usadas apenas durante o desenvolvimento.
# ===============================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Ferramentas de Geração de Código (VERSÕES ATUALIZADAS)
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  swagger_dart_code_generator: ^3.0.1 # <-- A MUDANÇA PRINCIPAL
  flutter_launcher_icons: ^0.13.1
  chopper_generator: ^6.0.0

# ===============================================================
# CONFIGURAÇÃO DO FLUTTER
# ===============================================================
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/event_register_image.jpg
    - assets/event.png

# ===============================================================
# CONFIGURAÇÃO DO FLUTTER LAUNCHER ICONS
# ===============================================================
flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
